### ISSUE TITLE
Missing Keto Soylent Supplier

### ISSUE THREAD

**Issue by StefanPatatu** [cortesimone/soylent-europe#1]
Hi,

I'm looking to get into soylent, but I don't want to give up on keto. Please add any known keto soylent suppliers to the list.

And kudos for the repo!

**Comment by cortesimone** [comment]
AFAIK no other manufacturers of Keto diet - complete meal replacement are available for purchase in Europe, just Keto One. Am I missing someone?

**Comment by StefanPatatu** [comment]
No idea. I was hoping you know of some suppliers I am not aware of. KetoOne seems to have huge shipping costs for Europe.

**Comment by cortesimone** [comment]
I'll volunteer to go to the USA and pickup a box for 1/10 of what they charge :)
